# Generated by Django 5.0.1 on 2025-01-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
