# Generated by Django 5.0.1 on 2025-02-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructorDashboard", "0001_initial"),
        ("signup", "0004_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="signup.instructor"
            ),
        ),
        migrations.DeleteModel(
            name="Instructor",
        ),
    ]
